### PR TITLE
Support Cloud Firestore withConverter

### PR DESCRIPTION
**Pull request by LucaDillenburg**
### Support for Cloud Firestore type annotation and ```withConverter``` method
- **Problem:** The last version of the package did not work well with the new ```Repository<T>``` and ```Query<T>``` types, because the code was not type annotated. Also, it couldn't work with the ```withConverter``` method from the ```cloud_firestore``` package.
- **Solution**: The code was refactored to add type annotation and another class was created to both:
1. Maintain compatibility with the last version
2. Enable users to use the package with the ```withConverter``` method with little to no change. As explained in the README (I added only as a side note but it have more emphasis), the ```GeoFireCollectionWithConverterRef<T>``` class can be used instead of the original ```GeoFireCollectionRef``` with the only change needed to ```within``` method that now requires an extra parameter to actually get the ```GeoPoint``` from the ```T``` class.

### Minor Tweaks
- Linting was added and the warnings were resolved
- Static types were prioritized instead of dynamic types

It works with the new version of Flutter in Stable (Flutter 2.5), so it might be related to #4 .

I would love to hear your feedbacks. :)

### CODE REVIEW

**Comment by cedvdb** [comment]
Maybe this could be submitted on https://github.com/DarshanGowda0/GeoFlutterFire

**Comment by cedvdb** [comment]
Well it's the one that was updated last and it seems like those are both similar so maybe it would be not much work to submit it there too. It's a bit hit or miss whit those solo maintainers packages anyway

**Comment by LucaDillenburg** [comment]
> Well it's the one that was updated last and it seems like those are both similar so maybe it would be not much work to submit it there too. It's a bit hit or miss whit those solo maintainers packages anyway when the pull requests will be merged. The original package seems like a safer bet imo.

Alright then :)

**Comment by cedvdb** [comment]
I don't think this required closing here though

**Pull request closed without merging**
